# Broadcasting

Broadcasting es una funcionalidad de Numpy para operaciones aritméticas en arrays de diferentes tamaños y formas.  
En lugar de crear copias para que los tamaños coincidan, extiende los arrays más pequeños a la forma del array más grande sin duplicar los datos.  
Esto permite realizar operaciones elementales entre arrays de distintos tamaños.


In [8]:
import numpy as np
prices = np.array([100,200,300])
discount = np.array([0.1])
#Aplico un solo valor a cada una de las entradas, es como la multiplicación de un vector por un escalar.
disc_price = discount * prices #El orden es irrelevante, no altera
print('Vector x Escalar: ', disc_price)

Vector x Escalar:  [10. 20. 30.]


In [9]:
prices = np.random.randint(100,200, size=(3,3))
discount = np.array([10,20,30])
disc_prices = prices + discount
print('Matriz aleatoria:\n', prices)
print('Resultado de suma de Matriz con Vector:\n', disc_prices)

Matriz aleatoria:
 [[130 169 137]
 [136 154 108]
 [170 145 131]]
Resultado de suma de Matriz con Vector:
 [[140 189 167]
 [146 174 138]
 [180 165 161]]


# Operaciones lógicas con Numpy
- Método all, return bool
- Método any (algún elemento), return bool

In [10]:
array = np.array([1,2,3,4,5])
print(np.all(array > 0))
print(np.any(array > 4))

True
True


En Numpy tambien tenemos el concepto de "Concatenación" que nos permite unir 1 o mas arrays para obtener uno solo

In [12]:
A = np.array([1,2,3])
B = np.array([4,5,6])
concatenated = np.concatenate((A, B)) #El argumento debe de ir entre (), imagina que es una tupla lo que se concatena, algo que por supuesto no pasaría en Python
print('Concatenación de, ', A, 'con ', B, 'igual a: ', concatenated)

Concatenación de,  [1 2 3] con  [4 5 6] igual a:  [1 2 3 4 5 6]


# Stacking
Nos permite apilar arrays o darles otra dimensionalidad especificandole lo que queremos


In [14]:
stacked_v = np.vstack((A,B)) #Lo mismo, el argumento va dentro de parentesis.
print('Stacked de manera vertical de A y B: ', stacked_v)
stacked_h = np.hstack((A,B))
print('Stacked de manera horizontal de A y B: ', stacked_h)

Stacked de manera vertical de A y B:  [[1 2 3]
 [4 5 6]]
Stacked de manera horizontal de A y B:  [1 2 3 4 5 6]


# Split
Por último veremos la división de los arrays, si tenemos un array grande lo podemos dividir en vectores/arrays con menos elementos

In [16]:
array_c = np.arange(1,10) #Recuerda que termina en 9
split_array = np.split(array_c, 3) #Argumentos: array a splitear y en cuantas divisiones
print(array)
print('Array spliteado: ', split_array)
#Ten cuidado con: ValueError: array split does not result in an equal division

[1 2 3 4 5]
Array spliteado:  [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
