# Broadcasting

Broadcasting es una funcionalidad de Numpy para operaciones aritméticas en arrays de diferentes tamaños y formas.  
En lugar de crear copias para que los tamaños coincidan, extiende los arrays más pequeños a la forma del array más grande sin duplicar los datos.  
Esto permite realizar operaciones elementales entre arrays de distintos tamaños.


In [1]:
import numpy as np
prices = np.array([100,200,300])
discount = np.array([0.1])
#Aplico un solo valor a cada una de las entradas, es como la multiplicación de un vector por un escalar.
disc_price = discount * prices #El orden es irrelevante, no altera
print('Vector x Escalar: ', disc_price)

Vector x Escalar:  [10. 20. 30.]


In [9]:
prices = np.random.randint(100,200, size=(3,3))
discount = np.array([10,20,30])
disc_prices = prices + discount
print('Matriz aleatoria:\n', prices)
print('Resultado de suma de Matriz con Vector:\n', disc_prices)

Matriz aleatoria:
 [[130 169 137]
 [136 154 108]
 [170 145 131]]
Resultado de suma de Matriz con Vector:
 [[140 189 167]
 [146 174 138]
 [180 165 161]]


# Operaciones lógicas con Numpy
- Método all, return bool
- Método any (algún elemento), return bool

In [10]:
array = np.array([1,2,3,4,5])
print(np.all(array > 0))
print(np.any(array > 4))

True
True


En Numpy tambien tenemos el concepto de "Concatenación" que nos permite unir 1 o mas arrays para obtener uno solo

In [12]:
A = np.array([1,2,3])
B = np.array([4,5,6])
concatenated = np.concatenate((A, B)) #El argumento debe de ir entre (), imagina que es una tupla lo que se concatena, algo que por supuesto no pasaría en Python
print('Concatenación de, ', A, 'con ', B, 'igual a: ', concatenated)

Concatenación de,  [1 2 3] con  [4 5 6] igual a:  [1 2 3 4 5 6]


# Stacking
Nos permite apilar arrays o darles otra dimensionalidad especificandole lo que queremos


In [14]:
stacked_v = np.vstack((A,B)) #Lo mismo, el argumento va dentro de parentesis.
print('Stacked de manera vertical de A y B: ', stacked_v)
stacked_h = np.hstack((A,B))
print('Stacked de manera horizontal de A y B: ', stacked_h)

Stacked de manera vertical de A y B:  [[1 2 3]
 [4 5 6]]
Stacked de manera horizontal de A y B:  [1 2 3 4 5 6]


# Split
Por último veremos la división de los arrays, si tenemos un array grande lo podemos dividir en vectores/arrays con menos elementos

In [16]:
array_c = np.arange(1,10) #Recuerda que termina en 9
split_array = np.split(array_c, 3) #Argumentos: array a splitear y en cuantas divisiones
print(array)
print('Array spliteado: ', split_array)
#Ten cuidado con: ValueError: array split does not result in an equal division

[1 2 3 4 5]
Array spliteado:  [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


# Unique
Indica que elementos hay dentro de un array cualitativo sin repetirse, podemos ademas contar cuantas veces aparece

In [15]:
responses = np.array(['bueno', 'excelente', 'malo', 'bueno', 'excelente', 'malo', 'bueno', 'excelente', 'malo'])
print('Respuestas: ', np.unique(responses))

#Para el conteo analiza que obtenemos dos variables, digamos metidas dentro de una clase de tupla, esto porque esta dentro de paréntesis, es para darnos una idea de que podemos meter ambos retornos en dos variables por separado para interpretar mejor los resultados...
count = np.unique(responses, return_counts=True)
print('Dentro de una variable: ', count)
print('Dividido en dos variables...')
elements, count = np.unique(responses, return_counts=True)
print('Elementos: ', elements)
print('Counts: ', count)
print('Zip es resultado de una clase, con tuple mostramos el resultado: ', tuple(zip(elements, count))) #Es un poco mas sucia la información.

Respuestas:  ['bueno' 'excelente' 'malo']
Dentro de una variable:  (array(['bueno', 'excelente', 'malo'], dtype='<U9'), array([3, 3, 3]))
Dividido en dos variables...
Elementos:  ['bueno' 'excelente' 'malo']
Counts:  [3 3 3]
Zip es resultado de una clase, con tuple mostramos el resultado:  ((np.str_('bueno'), np.int64(3)), (np.str_('excelente'), np.int64(3)), (np.str_('malo'), np.int64(3)))


# Copias y vistas
Hay que ser cuidadosos con las modificaciones que realizamos dentro de un array pues podemos compremeter la modificación de un array "original"

In [7]:
print('Vistas de arrays...')
array_x = np.arange(10)
view_y = array_x[1:3] #Simplemente quiero ver los elementos dentro de esos índices del array_x original.
print(array_x)
print(view_y)
#Hasta aquí todo normal

#Ahora, si yo modifico el array original pues tambien se vería afectada la vista de elementos/consulta de elementos que realicé (view_y)
array_x[1:3] = [10,11]
print(array_x)
print(view_y)
#Y esto puede ser un problema, todo esto radica en memoria, la solución es la sigueinte:

print('Copias de arrays...')
array_x = np.arange(10)
copy_x = array_x[1:3]
#Hasta ahorita todo normal
print(array_x)
print(copy_x)
#Realizo mi modificación
array_x[1:3] = [11,10]
print(array_x)
print(view_y)


Vistas de arrays...
[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]
Copias de arrays...
[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 11 10  3  4  5  6  7  8  9]
[10 11]


# Transformación de Arrays: Reshape y Manipulación

En algebra lineal la transposición de matrices es una operación fundamental para la solucion de sistema de ecuaciones.
Invertir nuestros arrays de dimensión 2 puede ser $\text{crucial para algorítmos de procesamiento de datos...}
En numpy esas operaciones no solo son posibles si no que son eficientes y fáciles de implemental, aprenderemos a transponer y cambiar forma de matrices además de invertir y aplanar arrays multidimensionales.

In [19]:
matrix = np.array([[1,2,3], [4,5,6], [1,2,3]])
transposed_matrix = matrix.T
print('Matriz:\n', matrix)
print('Transpuesta:\n', transposed_matrix)

Matriz:
 [[1 2 3]
 [4 5 6]
 [1 2 3]]
Transpuesta:
 [[1 4 1]
 [2 5 2]
 [3 6 3]]


# Reshape
Permite cambiar la forma de un array SIN CAMBIAR SUS DATOS. Es importante asegurarse que el número total de elementos permanezca constante... por ejemplo, un array de 2 elementos puede ser remodelado en una matriz 3x4, 4x3, 2x6 pero NO en una de dimensión 5x3

In [21]:
#Crearemos entonces un array de 12 elementos...
array = np.arange(1, 13)
reshaped_array = array.reshape(3,4)
print('Array: ', array)
print('Reshaped:\n', reshaped_array)


Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Reverse
Modificaciones a los elementos de un array.
Podemos invertir un array, como un algortimo de ordenamiento.

In [22]:
reversed_array = array[::-1] #Queremos que vaya de inicio a fin (::) y la manera en la que irá iterando será de -1 en -1, es decir que empieza con el -1, de ahí con el -2 y así sucesivamente hasta el inicio.
print('Reversed Array: ', reversed_array)

Reversed Array:  [12 11 10  9  8  7  6  5  4  3  2  1]


# Flattening
Se ve bastante en el mundo de la IA 
Cuando nececesitas un forma de datos LINEAL (digamos en forma de veector en vez de una matriz) para ciertos algorítmos de procesamiento y analisis, flattening es un procedimiento que transforma un array multidimensional a uni-dimensional.

Un caso específico del uso del flattening es en Deep Learning cuando tenemos una imagen de 64x64 y tenemos la matriz de pixeles, para pasar esta información a cada una de las neuronas de la red neuronal tenemos que aplanar la información para poder entrenar el modelo.

In [23]:
print('Matrix:\n', matrix)
flattened_array = matrix.flatten() #No recive argumentos.
#Recuerda que la lectura es primero en filas.
print('Matriz uni-dimensional: ', flattened_array)


Matrix:
 [[1 2 3]
 [4 5 6]
 [1 2 3]]
Matriz uni-dimensional:  [1 2 3 4 5 6 1 2 3]
